# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI2.ui'
#
# Created: Mon May  7 15:33:22 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 654)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/PNG_Files/Network/Disconnected.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.mainWidget = QtGui.QWidget(MainWindow)
        self.mainWidget.setObjectName(_fromUtf8("mainWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.mainWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fileTabs = QtGui.QTabWidget(self.mainWidget)
        self.fileTabs.setObjectName(_fromUtf8("fileTabs"))
        self.localFilesTab = QtGui.QWidget()
        self.localFilesTab.setObjectName(_fromUtf8("localFilesTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.localFilesTab)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeWidget = QtGui.QTreeWidget(self.localFilesTab)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.header().setDefaultSectionSize(200)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.fileTabs.addTab(self.localFilesTab, _fromUtf8(""))
        self.projectFilesTab = QtGui.QWidget()
        self.projectFilesTab.setObjectName(_fromUtf8("projectFilesTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.projectFilesTab)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.projectFilesTreeWidget = QtGui.QTreeWidget(self.projectFilesTab)
        self.projectFilesTreeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.projectFilesTreeWidget.setObjectName(_fromUtf8("projectFilesTreeWidget"))
        self.projectFilesTreeWidget.header().setDefaultSectionSize(120)
        self.verticalLayout.addWidget(self.projectFilesTreeWidget)
        self.fileTabs.addTab(self.projectFilesTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.fileTabs)
        MainWindow.setCentralWidget(self.mainWidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setIconSize(QtCore.QSize(48, 48))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.actionSettings = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/PNG_Files/Hardware/Computer.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon1)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionCheckout = QtGui.QAction(MainWindow)
        self.actionCheckout.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/PNG_Files/Misc/Download.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheckout.setIcon(icon2)
        self.actionCheckout.setObjectName(_fromUtf8("actionCheckout"))
        self.actionCheckin = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/PNG_Files/Misc/Upload.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheckin.setIcon(icon3)
        self.actionCheckin.setObjectName(_fromUtf8("actionCheckin"))
        self.actionCache_to_Alembic = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/PNG_Files/Misc/alembic_logo_Darkest.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCache_to_Alembic.setIcon(icon4)
        self.actionCache_to_Alembic.setObjectName(_fromUtf8("actionCache_to_Alembic"))
        self.actionInstall = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/PNG_Files/Folders/Favourites.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInstall.setIcon(icon5)
        self.actionInstall.setObjectName(_fromUtf8("actionInstall"))
        self.actionUpdate_Plugins = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/PNG_Files/Misc/Search.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate_Plugins.setIcon(icon6)
        self.actionUpdate_Plugins.setObjectName(_fromUtf8("actionUpdate_Plugins"))
        self.actionOpen_File = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/PNG_Files/File_Formats/format.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_File.setIcon(icon7)
        self.actionOpen_File.setObjectName(_fromUtf8("actionOpen_File"))
        self.toolBar.addAction(self.actionCheckout)
        self.toolBar.addAction(self.actionInstall)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCheckin)
        self.toolBar.addAction(self.actionOpen_File)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCache_to_Alembic)
        self.toolBar.addAction(self.actionUpdate_Plugins)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSettings)

        self.retranslateUi(MainWindow)
        self.fileTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Chasm Project Utility", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "File Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Check Out Time", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Last Opened", None, QtGui.QApplication.UnicodeUTF8))
        self.fileTabs.setTabText(self.fileTabs.indexOf(self.localFilesTab), QtGui.QApplication.translate("MainWindow", "My Checked Out Files", None, QtGui.QApplication.UnicodeUTF8))
        self.projectFilesTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "File Name", None, QtGui.QApplication.UnicodeUTF8))
        self.projectFilesTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Locked", None, QtGui.QApplication.UnicodeUTF8))
        self.projectFilesTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Checked In by:", None, QtGui.QApplication.UnicodeUTF8))
        self.projectFilesTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Check In Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.projectFilesTreeWidget.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Ready For Use", None, QtGui.QApplication.UnicodeUTF8))
        self.fileTabs.setTabText(self.fileTabs.indexOf(self.projectFilesTab), QtGui.QApplication.translate("MainWindow", "Project Files", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setToolTip(QtGui.QApplication.translate("MainWindow", "Configure Your Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheckout.setText(QtGui.QApplication.translate("MainWindow", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheckout.setToolTip(QtGui.QApplication.translate("MainWindow", "Checkout Project File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheckin.setText(QtGui.QApplication.translate("MainWindow", "Checkin", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheckin.setToolTip(QtGui.QApplication.translate("MainWindow", "Checkin a Local File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCache_to_Alembic.setText(QtGui.QApplication.translate("MainWindow", "Alembic", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInstall.setText(QtGui.QApplication.translate("MainWindow", "Install", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInstall.setToolTip(QtGui.QApplication.translate("MainWindow", "Install / Flatten a File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_Plugins.setText(QtGui.QApplication.translate("MainWindow", "Update Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_Plugins.setToolTip(QtGui.QApplication.translate("MainWindow", "Update Project Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_File.setText(QtGui.QApplication.translate("MainWindow", "Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_File.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a Local or Project File in Maya or Houdini", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

